# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWinSizePolicyLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 294)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 80, 89, 25))
        self.pushButton.setObjectName("pushButton")
        # 打印pushButton控件的期望尺寸
        push_button_width = self.pushButton.sizeHint().width()
        push_button_height = self.pushButton.sizeHint().height()
        print('pushButton控件期望尺寸的宽度：{}px'.format(push_button_width))
        print('pushButton控件期望尺寸的高度：{}px'.format(push_button_height))
        """
        pushButton控件期望尺寸的宽度：48px
        pushButton控件期望尺寸的高度：25px
        """
        # 打印pushButton控件的最小期望尺寸
        push_button_minimum_width = self.pushButton.minimumSizeHint().width()
        push_button_minimum_height = self.pushButton.minimumSizeHint().height()
        print('pushButton控件最小期望尺寸的宽度：{}px'.format(push_button_minimum_width))
        print('pushButton控件最小期望尺寸的高度：{}px'.format(push_button_minimum_height))
        """
        pushButton控件最小期望尺寸的宽度：48px
        pushButton控件最小期望尺寸的高度：25px
        """
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 80, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 80, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 140, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        # 打印line_Edit控件的期望尺寸
        line_Edit_width = self.lineEdit.sizeHint().width()
        line_Edit_height = self.lineEdit.sizeHint().height()
        print('lineEdit控件期望尺寸的宽度：{}px'.format(line_Edit_width))
        print('lineEdit控件期望尺寸的高度：{}px'.format(line_Edit_height))
        """
        lineEdit控件期望尺寸的宽度：142px
        lineEdit控件期望尺寸的高度：25px
        """
        # 打印line_Edit控件的最小期望尺寸
        line_Edit_minimum_width = self.lineEdit.minimumSizeHint().width()
        line_Edit_minimum_height = self.lineEdit.minimumSizeHint().height()
        print('lineEdit控件最小期望宽度：{}px'.format(line_Edit_minimum_width))
        print('lineEdit控件最小期望高度：{}px'.format(line_Edit_minimum_height))
        """
        lineEdit控件最小期望宽度：59px
        lineEdit控件最小期望高度：25px
        """
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Buton1"))
        self.pushButton_2.setText(_translate("MainWindow", "Buton2"))
        self.pushButton_3.setText(_translate("MainWindow", "Buton3"))
